### ISSUE TITLE
check storage area at node where 1d lateral, 1d bc or pump inflow is attached to (should be > threshold)

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-modelchecker#246]
@Jonasvsl commented on [Mon Nov 14 2022](https://github.com/nens/threedi-api/issues/1804)

**Comment by leendertvanwolfswinkel** [comment]
Not 100% sure, but I think any connection node (and its storage area) at a discharge, velocity or sommerfeld boundary is ignored and thus not relevant for this check. Is that right @martijn-siemerink

**Comment by leendertvanwolfswinkel** [comment]
Defining a threshold is really tricky I think. Perhaps something like 'water level should not rise >= 1 m in one second'? Which we could make dependent on the max discharge in the lateral's timeseries, or the pump capacity. I am a bit hesitant with regard to the first one, because it means we further mix scenario information and schematisation data.

So perhaps we should simplify this to "Check that storage_area  > pump_capacity / 1000 for pump end nodes"?  (/1000 because pump_capacity is in L/s)

**Comment by Patrick-Nijman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-3Di-5ef60eff1973dd0024268b90/issues/nens/threedi-modelchecker/246?planning-poker) with Zenhub @elisallenens

**Comment by elisallenens** [comment]
This issue seems like it's not quite clear yet on the precise implementation; making an estimate would be easier once that is decided on.

**Comment by leendertvanwolfswinkel** [comment]
Ok, let me redefine the ticket than:

- Check that storage_area > pump_capacity / 1000 for pump end nodes

**Comment by elisallenens** [comment]
Also isn't this the same as https://github.com/nens/threedi-modelchecker/issues/245?

**Comment by leendertvanwolfswinkel** [comment]
The difference is that for the end node, we cannot calculate volume as we can do for the start node
