### ISSUE TITLE
check if size of cross sections are not too small

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-modelchecker#251]
@Jonasvsl commented on [Mon Nov 14 2022](https://github.com/nens/threedi-api/issues/1799)

**Comment by Jonasvsl** [comment]
too small is a subjective thing. Is there a  defailt that we need to set for this?

**Comment by leendertvanwolfswinkel** [comment]
I think that any cross section with a diameter < 0.100 m is wrong in 99% of cases. This kind of diameter does not exist in sewer systems; in open water systems it would also be a bit ridiculous. 

So perhaps surface area of cross sections should always be `A > pi()*(0.1/2)^2` ?

**Comment by Overmeen** [comment]
I would say the cross sectional area proposed by @leendertvanwolfswinkel  is a good setting for pipes, culverts and orifices.

I think wat is relevant for open water systems is the transition from one cross section to the other. 

When I run my control checks for WDOD models, I put the threshold on 0.1 m2 and it gives me back many channels. Somehow, very small streams have made it into a 1D channel. I think this is not the problem if their are all adjacent cross sections.

It becomes questionable if a larger channel would converge into a very small cross sectional area or vice versa. This is most likely to be a user input mistake. The check could be on a certain factor of narrowing. For instance a factor of narrowing of 10. When going from 5 m2 to 0.5 m2 or smaller. Even though, 0.5 m2 may not be crazy small, in this situation it could lead to significant backwater curve and cause flooding that may just be caused by input mistakes.

I would like to propose a division of this tickets into two tickets; one for channels and one for pipes and structures. Let me know what you think.

**Comment by Jonasvsl** [comment]
@Overmeen this might be very hard to check, especially when you have crossings these changes that you mentioned might even be correct. 

Do I understand correcly that you have 1D-2D simulation with a 1D channel with a cross section of 0.1 m2? I'm trying to picture what that looks like in the outside world. ar eyou sure those are meant to be in the schematisation?

**Comment by Overmeen** [comment]
@Jonasvsl hmm yeah you probably right about the crossing, didn't think that one through. A visual check would then make more sense based on the cross sectional area, if this could be added to the standard stylings @leendertvanwolfswinkel 

Well, we are now checking the WDOD nbw models for required improvements. And somehow very shallow channels have made it into the schematisation, +- 10 cm deep. I don't think they should be in the schematisation, but I don't think this check addresses the real bottlenecks. Wrong profiles in the larger waterways have more impact.

**Comment by Jonasvsl** [comment]
Can wrong profiles, or sudden changes in profile, not be seen when analysing the results of the simulation?
Isn't it easier to start doing sanity checks on results?

E.g. 
- pipe velocity should never be higher than 2 m/s
- Hydraulic lines should never be steeper than x m/m
etc?

**Comment by leendertvanwolfswinkel** [comment]
I think the example of @Overmeen only underlines that our simple approach with a 0.1 m2 threshold is a good one; note that we just want to give a warning, not an error. Warnings should be given for situations where "I don't think they should be in the schematisation" applies.

And no, it will not solve/capture all situations, but it is a valuable check

**Comment by leendertvanwolfswinkel** [comment]
Checking differences between cross-sections from one channel to the next may be relevant, but the issue here is that going from small to big is ok, while going from big to small is not ok. The only way to know which case you are dealing with, is if you know the flow direction, i.e. you need simulation results to analyse this. So this is not really something for the schematisation checker, but for a ((distant) future) simulation results checker

**Comment by Jonasvsl** [comment]
agree. let's stick to the simpel one that Leendert proposed

**Comment by elisallenens** [comment]
Yesterday Martijn Siemerink looked at this; calculating the area for things like tabulated trapeziums would require shapely as an extra dependency, so the check will instead be as follows:

The minimum diameter is $x$ such that $0.1 = \pi (0.5x)^2$.
For closed cross-sections, the width and height must both be more than $x$.
For open cross-sections, the width must be more than $x$.
